//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int aboutID { get; set; }
        public string aboutDescription { get; set; }
        public string aboutEditörs { get; set; }
        public string aboutSales { get; set; }
        public Nullable<bool> isTheAboutActive { get; set; }
    }
}
