//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestSeller
    {
        public int bestSellerID { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<bool> isTheBestSellerActive { get; set; }
        public string bestSellerDescription { get; set; }
    }
}
