//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Employees = new HashSet<Employees>();
            this.Categories = new HashSet<Categories>();
            this.Customers = new HashSet<Customers>();
            this.Writers = new HashSet<Writers>();
        }
    
        public int bookID { get; set; }
        public string bookName { get; set; }
        public string bookYearOfPublication { get; set; }
        public Nullable<int> publisherID { get; set; }
        public Nullable<decimal> bookPrice { get; set; }
        public Nullable<byte> bookPageCount { get; set; }
        public Nullable<byte> bookStockQty { get; set; }
        public Nullable<int> languageID { get; set; }
        public string bookDescription { get; set; }
        public Nullable<bool> isTheBookActive { get; set; }
        public string bookCoverPhoto { get; set; }
        public string bookISBN { get; set; }
    
        public virtual tbl_Languages tbl_Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Writers> Writers { get; set; }
    }
}
