//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contactID { get; set; }
        public string contactNumber { get; set; }
        public string contactAddress { get; set; }
        public string contactEmail { get; set; }
        public Nullable<bool> isTheContactActive { get; set; }
    }
}
