//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Books = new HashSet<Books>();
        }
    
        public int customerID { get; set; }
        public string customerName { get; set; }
        public string customerSurname { get; set; }
        public string customerTCIdentityNumber { get; set; }
        public string customerEmail { get; set; }
        public string customerPhone { get; set; }
        public string customerAddress { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> districtID { get; set; }
        public string customerPostCode { get; set; }
        public Nullable<bool> isTheCustomerActive { get; set; }
        public string customerPassword { get; set; }
        public Nullable<decimal> customerCurrentAccount { get; set; }
        public Nullable<System.DateTime> customerBirthDate { get; set; }
        public Nullable<int> genderID { get; set; }
        public string customerDescription { get; set; }
        public Nullable<bool> isTheCustomerInstitutional { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual tbl_District tbl_District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books> Books { get; set; }
    }
}
