//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int discountID { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> discountPrice { get; set; }
        public Nullable<int> discountRatio { get; set; }
        public Nullable<int> writerID { get; set; }
        public string isTheDiscountActive { get; set; }
        public string discountDescription { get; set; }
    }
}
