//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Books = new HashSet<Books>();
            this.tbl_Languages = new HashSet<tbl_Languages>();
        }
    
        public int employeeID { get; set; }
        public string employeeName { get; set; }
        public string employeeSurname { get; set; }
        public string employeePhone { get; set; }
        public string employeeTCIdentityNumber { get; set; }
        public string employeeSgkNumber { get; set; }
        public Nullable<System.DateTime> employeeStartingDateOfEmployment { get; set; }
        public Nullable<System.DateTime> employeeEndingDateOfEmployment { get; set; }
        public Nullable<decimal> employeeSalary { get; set; }
        public Nullable<int> titleID { get; set; }
        public string employeeAddress { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> districtID { get; set; }
        public Nullable<bool> isTheEmployeeActive { get; set; }
        public Nullable<System.DateTime> employeeBirthDate { get; set; }
        public string employeeContactNumber { get; set; }
        public Nullable<int> genderID { get; set; }
        public string employeeDescription { get; set; }
        public string employeeEmail { get; set; }
        public Nullable<int> employeeReportEmployeeID { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual tbl_District tbl_District { get; set; }
        public virtual Titles Titles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books> Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Languages> tbl_Languages { get; set; }
    }
}
