//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int mailID { get; set; }
        public string mailNameSurname { get; set; }
        public string mailAddress { get; set; }
        public string mailMessage { get; set; }
        public string mailSubject { get; set; }
    }
}
