//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_BookStore2Entities : DbContext
    {
        public DB_BookStore2Entities()
            : base("name=DB_BookStore2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_District> tbl_District { get; set; }
        public virtual DbSet<tbl_Languages> tbl_Languages { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
        public virtual DbSet<Writers> Writers { get; set; }
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<BestSeller> BestSeller { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<userType> userType { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_BookStore_Result> sp_BookStore(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore_Result>("sp_BookStore", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore1_Result> sp_BookStore1(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore1_Result>("sp_BookStore1", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore10_Result> sp_BookStore10(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore10_Result>("sp_BookStore10", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore17_Result> sp_BookStore17(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore17_Result>("sp_BookStore17", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore18_Result> sp_BookStore18(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore18_Result>("sp_BookStore18", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore19_Result> sp_BookStore19(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore19_Result>("sp_BookStore19", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore2_Result> sp_BookStore2(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore2_Result>("sp_BookStore2", categoryIDParameter);
        }
    
        public virtual ObjectResult<sp_BookStore20_Result> sp_BookStore20(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore20_Result>("sp_BookStore20", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore21_Result> sp_BookStore21(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore21_Result>("sp_BookStore21", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore22_Result> sp_BookStore22(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore22_Result>("sp_BookStore22", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore23_Result> sp_BookStore23(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore23_Result>("sp_BookStore23", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore24_Result> sp_BookStore24(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore24_Result>("sp_BookStore24", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore25_Result> sp_BookStore25(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore25_Result>("sp_BookStore25", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore26_Result> sp_BookStore26(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore26_Result>("sp_BookStore26", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore27_Result> sp_BookStore27(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore27_Result>("sp_BookStore27", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore3_Result> sp_BookStore3(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore3_Result>("sp_BookStore3", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore30_Result> sp_BookStore30(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore30_Result>("sp_BookStore30", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore4_Result> sp_BookStore4(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore4_Result>("sp_BookStore4", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore5_Result> sp_BookStore5(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore5_Result>("sp_BookStore5", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore6_Result> sp_BookStore6(Nullable<int> categoryID, Nullable<int> writerID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerIDParameter = writerID.HasValue ?
                new ObjectParameter("writerID", writerID) :
                new ObjectParameter("writerID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore6_Result>("sp_BookStore6", categoryIDParameter, writerIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore7_Result> sp_BookStore7(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore7_Result>("sp_BookStore7", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore8_Result> sp_BookStore8(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore8_Result>("sp_BookStore8", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStore9_Result> sp_BookStore9(Nullable<int> categoryID, string writerNameSurname)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStore9_Result>("sp_BookStore9", categoryIDParameter, writerNameSurnameParameter);
        }
    
        public virtual ObjectResult<sp_BookStoreExample_Result> sp_BookStoreExample(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookStoreExample_Result>("sp_BookStoreExample", categoryIDParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_getBestSellerListCategoryID_Result> sp_getBestSellerListCategoryID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBestSellerListCategoryID_Result>("sp_getBestSellerListCategoryID", idParameter);
        }
    
        public virtual ObjectResult<sp_getBookListWithCategoryID_Result> sp_getBookListWithCategoryID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookListWithCategoryID_Result>("sp_getBookListWithCategoryID", idParameter);
        }
    
        public virtual ObjectResult<sp_getBookListWithKategoriID_Result> sp_getBookListWithKategoriID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookListWithKategoriID_Result>("sp_getBookListWithKategoriID", idParameter);
        }
    
        public virtual ObjectResult<sp_getBookListWithPublisherID_Result> sp_getBookListWithPublisherID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookListWithPublisherID_Result>("sp_getBookListWithPublisherID", idParameter);
        }
    
        public virtual ObjectResult<sp_getBookListWithWriterID_Result> sp_getBookListWithWriterID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookListWithWriterID_Result>("sp_getBookListWithWriterID", idParameter);
        }
    
        public virtual ObjectResult<sp_getBookWriterOrCategoryName_Result> sp_getBookWriterOrCategoryName(string categoryName, string writerNameSurname, string bookName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var writerNameSurnameParameter = writerNameSurname != null ?
                new ObjectParameter("writerNameSurname", writerNameSurname) :
                new ObjectParameter("writerNameSurname", typeof(string));
    
            var bookNameParameter = bookName != null ?
                new ObjectParameter("bookName", bookName) :
                new ObjectParameter("bookName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getBookWriterOrCategoryName_Result>("sp_getBookWriterOrCategoryName", categoryNameParameter, writerNameSurnameParameter, bookNameParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
