//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publishers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publishers()
        {
            this.Categories = new HashSet<Categories>();
        }
    
        public int publisherID { get; set; }
        public string publisherName { get; set; }
        public string publisherAddress { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> districtID { get; set; }
        public string publisherPhone { get; set; }
        public string publisherAuthorizedNameSurname { get; set; }
        public string publisherEmail { get; set; }
        public Nullable<bool> isThePublisherActive { get; set; }
        public string publisherDescription { get; set; }
        public string publisherPostCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
