//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int salesID { get; set; }
        public string salesBillNumber { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<decimal> salesPrice { get; set; }
        public Nullable<byte> salesVatRate { get; set; }
        public Nullable<System.DateTime> salesDate { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<bool> isTheSalesActive { get; set; }
        public string salesDescription { get; set; }
        public Nullable<byte> salesPiece { get; set; }
        public string salesAddress { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> districtID { get; set; }
        public string salesPostCode { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        public virtual tbl_District tbl_District { get; set; }
    }
}
