//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Writers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Writers()
        {
            this.Books = new HashSet<Books>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int writerID { get; set; }
        public string writerNameSurname { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> genderID { get; set; }
        public Nullable<bool> isTheWriterActive { get; set; }
        public string writerDescription { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual tbl_Country tbl_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books> Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
